wildfly:
  rules:
    - id: "LRA"
      title: "lra"
      body: "lra"
      directories:
        - microprofile/lra
      notify: [xstefank]
    - id: "health"
      title: "health"
      body: "health"
      directories:
        - microprofile/smallrye-health
        - health
  format:
    title-check:
      pattern: "\\[WFLY-\\d+\\]\\s+.*|WFLY-\\d+\\s+.*"
      message: "Wrong content of the title!"
    description:
      regexes:
        - pattern: "JIRA:\\s+https://issues.redhat.com/browse/WFLY-\\d+|https://issues.redhat.com/browse/WFLY-\\d+"
          message: "The PR description must contain a link to the JIRA issue"
    commits-quantity:
      quantity: "1-3"
      message: "Too many commits in PR!"
