wildfly:
  rules:
    - id: "this is id"
      title: "resteasy"
      notify:
        - random-person
    - id: "more useful id"
      title: "hibernate"
      notify: [ random-person ]

    - id: "last id"
      directories: [ src/main, src/test/org/acme/resources/* ]
      notify: [ another-random-person ]

  format:
    title-check:
      pattern: "\\[WFLY-\\d+\\]\\s+.*|WFLY-\\d+\\s+.*"
      message: "Wrong content of the title!"
    description:
      regexes:
        - pattern: "JIRA:\\s+https://issues.redhat.com/browse/WFLY-\\d+|https://issues.redhat.com/browse/WFLY-\\d+"
          message: "The PR description must contain a link to the JIRA issue"
    commits-quantity:
      quantity: "1-3"
      message: "Too many commits in PR!"
    commits-message:
      pattern: "\\[WFLY-\\d+\\]\\s+.*|WFLY-\\d+\\s+.*"
      message: "Wrong content of the title!"

  emails:
    - random-person@bar.baz
    - another-random-person@gmail.com