wildfly:
  rules:
    - title: "test"
      id: "some test id"
    - id: "another great id"
      body: "test"
      notify: [The-non-existing-user]
  format:
    title-check:
      pattern: "\\[TITLE-\\d+\\]\\s+.*|TITLE-\\d+\\s+.*"
    description:
      regexes:
        - pattern: "\\s+https://"
          message: "The PR description must contain a link."
    commits-quantity:
      quantity: "1-3"
      message: "Too many commits in this PR!"

  emails:
    - rastislavbudinsky@gmail.com
    - rbudinsk@redhat.com
    - foo@bar.baz
